"""
    geo.codes

    The alpha version of the [https://geo.codes](https://geo.codes) API service. See API documentation [here](https://geo.codes/docs/api). 10,000 free queries per month.  # noqa: E501

    The version of the OpenAPI document: 1.0.0-alpha
    Contact: help@geo.codes
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import geocodes
from geocodes.model.us_street_address import USStreetAddress


class TestUSStreetAddress(unittest.TestCase):
    """USStreetAddress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUSStreetAddress(self):
        """Test USStreetAddress"""
        # FIXME: construct object with mandatory attributes with example values
        # model = USStreetAddress()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
