# flake8: noqa

"""
    geo.codes

    The alpha version of the [https://geo.codes](https://geo.codes) API service. See API documentation [here](https://geo.codes/docs/api). 10,000 free queries per month.  # noqa: E501

    The version of the OpenAPI document: 1.0.0-alpha
    Contact: help@geo.codes
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from geocodes.api_client import ApiClient

# import Configuration
from geocodes.configuration import Configuration

# import exceptions
from geocodes.exceptions import OpenApiException
from geocodes.exceptions import ApiAttributeError
from geocodes.exceptions import ApiTypeError
from geocodes.exceptions import ApiValueError
from geocodes.exceptions import ApiKeyError
from geocodes.exceptions import ApiException
