"""
    geo.codes

    The alpha version of the [https://geo.codes](https://geo.codes) API service. See API documentation [here](https://geo.codes/docs/api). 10,000 free queries per month.  # noqa: E501

    The version of the OpenAPI document: 1.0.0-alpha
    Contact: help@geo.codes
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.address_api import AddressApi  # noqa: E501


class TestAddressApi(unittest.TestCase):
    """AddressApi unit test stubs"""

    def setUp(self):
        self.api = AddressApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_address_geocode(self):
        """Test case for v1_address_geocode

        Geocode an unstructured address string  # noqa: E501
        """
        pass

    def test_v1_address_structured_geocode(self):
        """Test case for v1_address_structured_geocode

        Geocode structured addresses  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
