"""
    geo.codes

    The alpha version of the [https://geo.codes](https://geo.codes) API service. See API documentation [here](https://geo.codes/docs/api). 10,000 free queries per month.  # noqa: E501

    The version of the OpenAPI document: 1.0.0-alpha
    Contact: help@geo.codes
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import geocodes
from geocodes.model.gcs_coordinate import GCSCoordinate
from geocodes.model.us_address import USAddress
globals()['GCSCoordinate'] = GCSCoordinate
globals()['USAddress'] = USAddress
from geocodes.model.geocoding import Geocoding


class TestGeocoding(unittest.TestCase):
    """Geocoding unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGeocoding(self):
        """Test Geocoding"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Geocoding()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
